In [170]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [171]:
ds = pd.read_csv('../new_data.csv')
# ds = ds.drop(ds[ds.viewCount >10000].index)
ds.head()

,videoId,channelId,channelTitle,title,description,categoryId,publishedAt,currentTime,life,definition,...,longitude,publicStatsViewable,privacyStatus,license,embeddable,commentCount,viewCount,favoriteCount,dislikeCount,likeCount
0,bjBwri_QujU,UCVcb5c_-h5HxMZobDTCzBkg,Paul Tech,LG Stylo 2 Plus Full Review is it worth it?,So this is my full detailed review for the LG ...,28,1.467334e+09,1.491935e+09,24601087,hd,...,NaN,1.0,public,youtube,1.0,706.0,144984.0,0.0,33.0,2059.0
1,y2jAD9G_aLs,UCs0NBBFNnMoOMdB1D9ZEbkg,はうんどちゃんねる,【衝撃】 爆発したらヤバい！！ベテルギウス超新星爆発して2つ目の太陽に？既に存在するか？嘘の...,【衝撃】 爆発したらヤバい！！ベテルギウス超新星爆発して2つ目の太陽に？既に存在するか？嘘の...,28,1.467332e+09,1.491935e+09,24603046,hd,...,NaN,1.0,public,youtube,1.0,19.0,55829.0,0.0,32.0,73.0
2,KsjUUIOOCNE,UCkLJqy2fWYqBhPinnJjqXrA,newsmexico com mx,Iglesia presbiteriana pide diálogo magisterial...,Visita Newsmexico.com.mx La iglesia Presbiteri...,25,1.467332e+09,1.491935e+09,24602827,sd,...,NaN,1.0,public,youtube,1.0,0.0,625.0,0.0,0.0,11.0
3,Bjd0fQMpLLE,UCqhrVgL7_SumSLwmStIFQhw,Canal INEHRM,Conferencia congreso anfictiónico de Panamá en...,Por: Mario Vázquez Olivera\n\nVisita nuestras ...,27,1.467333e+09,1.491935e+09,24601632,sd,...,NaN,1.0,public,youtube,1.0,0.0,302.0,0.0,0.0,5.0
4,4V1w27m3dEw,UCi4sUjs8u1pat9GMgp3pNlQ,Hatim ali ali,Hatim,NaN,22,1.467334e+09,1.491935e+09,24600518,sd,...,NaN,1.0,public,youtube,1.0,0.0,11.0,0.0,0.0,1.0

In [172]:
del ds['videoId']
del ds['channelId']
del ds['channelTitle']
del ds['title']
del ds['publishedAt']
del ds['currentTime']
del ds['caption']
del ds['allowed']
del ds['recordingDate']
del ds['allowedCount']
del ds['publicStatsViewable']
del ds['favoriteCount']
del ds['privacyStatus']
del ds['dimension']
del ds['latitude']
del ds['longitude']
del ds['definition']
del ds['durationCategory']
del ds['license']
del ds['licensedContent']
del ds['embeddable']
del ds['description']
del ds['categoryId']
ds.head()

       life  duration  commentCount  viewCount  dislikeCount  likeCount
0  24601087     592.0         706.0   144984.0          33.0     2059.0
1  24603046     396.0          19.0    55829.0          32.0       73.0
2  24602827     174.0           0.0      625.0           0.0       11.0
3  24601632    4327.0           0.0      302.0           0.0        5.0
4  24600518     134.0           0.0       11.0           0.0        1.0

In [173]:
ds = ds.dropna(subset=['likeCount', 'viewCount'])

ds['life'] = ds['life'].astype('uint')
ds['life'] = ds['life'].apply(lambda x: x/(60*60*24))

ds.head()

   life  duration  commentCount  viewCount  dislikeCount  likeCount
0   284     592.0         706.0   144984.0          33.0     2059.0
1   284     396.0          19.0    55829.0          32.0       73.0
2   284     174.0           0.0      625.0           0.0       11.0
3   284    4327.0           0.0      302.0           0.0        5.0
4   284     134.0           0.0       11.0           0.0        1.0

In [174]:
mean_Comm = ds['commentCount'].mean()
ds['commentCount'] = ds['commentCount'].fillna(int(mean_Comm))
ds.describe()

,life,duration,commentCount,viewCount,dislikeCount,likeCount
count,40870.000000,4.087000e+04,40870.000000,4.087000e+04,4.087000e+04,4.087000e+04
mean,167.768706,9.753229e+02,1814.119158,2.520658e+06,1.285949e+03,1.954893e+04
std,62.689663,3.644232e+04,10204.837803,1.913501e+07,1.033462e+04,1.088264e+05
min,1.000000,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00
25%,112.000000,1.610000e+02,0.000000,7.072500e+02,0.000000e+00,7.000000e+00
50%,174.000000,2.900000e+02,32.000000,2.876450e+04,1.500000e+01,1.800000e+02
75%,214.000000,6.567500e+02,665.000000,8.465642e+05,3.860000e+02,6.303000e+03
max,284.000000,7.357811e+06,646612.000000,1.407369e+09,1.072069e+06,5.702948e+06

In [175]:
data = np.asarray([ds['life'], ds['duration'], ds['commentCount'], ds['viewCount'], ds['dislikeCount'], ds['likeCount']]).T
data = (data - data.mean(axis=0))/data.std(axis=0)
print data.shape
corr = np.cov(data.T).astype('float')[-1]
print corr

(40870, 6)
[-0.01027544 -0.00185042  0.74584014  0.81464735  0.59119616  1.00002447]

In [179]:
records = np.asarray([ds['life'], ds['duration'], ds['commentCount'], ds['viewCount'], ds['dislikeCount']]).T
records = (records - records.mean(axis=0))/records.std(axis=0)
ans = np.asarray(ds['likeCount']).T

split = int(0.9*records.shape[0])
X_train = records[:split, :]
y_train = ans[:split]

X_test = records[split:, :]
y_test = ans[split:]

print X_train.shape, y_train.shape
print X_test.shape, y_test.shape

(36783, 5) (36783,)
(4087, 5) (4087,)

In [180]:
def dist(x1, x2):
    return np.sqrt(((x1-x2)**2).sum())           #divide this distance by range to normalize things?
    # return np.sqrt(0.5*((np.sqrt(x1) - np.sqrt(x2))**2).sum())
    

def knn(X_train, x, y_train, k=5):
    vals = []
    for ix in range(X_train.shape[0]):
        v = [dist(x, X_train[ix, :]), y_train[ix]]
        vals.append(v)
    
    updated_vals = sorted(vals, key=lambda x:x[0])
    pred_arr = np.asarray(updated_vals[:k])
    pred_arr = pred_arr[1]
    return pred_arr.mean(axis=0)

def whknn(x_train, x, y_train, k=5):
    vals = []
    for ix in range(x_train.shape[0]):
        di = dist(x, x_train[ix, :])
        wi = 1/(di + (10**(-6)))
        v = [wi, y_train[ix]]
        vals.append(v)

    updated_vals = sorted(vals, key=lambda x:x[0], reverse=True)
    pred_arr = np.asarray(updated_vals[:k])
    total_weight = pred_arr.sum(axis=0)[0]
    prod = 0
    for ix in range(pred_arr.shape[0]):
        prod += pred_arr[ix, 0]*pred_arr[ix, 1]
    prod /=total_weight
    return prod

In [ ]:
std = []
y_pred = []
for ix in range(X_test.shape[0]):
    q = X_test[ix]
    res = knn(X_train, q, y_train, k=4)
    y_pred.append(res)
    std.append(np.abs(res - y_test[ix]))
    # print ix, std[ix]

plt.figure(0)
plt.plot(std)
plt.show()
print np.mean(std)

In [ ]:
from sklearn.metrics import r2_score
print r2_score(y_test, y_pred)

In [ ]:
std = []
y_pred = []
for ix in range(X_test.shape[0]):
    q = X_test[ix]
    res = whknn(X_train, q, y_train, k=4)
    y_pred.append(res)
    std.append(np.abs(res - y_test[ix]))
    # print ix, std[ix]

plt.figure(0)
plt.plot(std)
plt.show()
print np.mean(std)

In [ ]:
from sklearn.metrics import r2_score
print r2_score(y_test, y_pred)